// Generated by https://quicktype.io

export interface Test {
    posts:    Post[];
    comments: Comment[];
    profile:  Profile;
}

export interface Comment {
    id:     number;
    body:   string;
    postId: number;
}

export interface Post {
    id:          number;
    ticker:      string;
    stockPrice:  string;
    timeElapsed: string;
}

export interface Profile {
    name: string;
}
